artifact_location: /home/ubuntu/Depending-Model-Inversion/train_face/218.155.110.67:5000/0
creation_time: 1690872448094
experiment_id: '0'
last_update_time: 1690872448094
lifecycle_stage: active
name: Default
